name: Postman Run

# Controls when the workflow will run
on: [push]

jobs:

  run-postman-test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4

      - name: Install Node
        uses: action/setup-node@v4
        with:
           node-version: '18'

      - name: Install Newman
        uses: npm install -g newman
        
      - name: Run postman Test
        uses: newmman run postman_tests\Books.postman_collection.json -e postman_tests\test.postman_environment.json
